# Generated by Django 4.2.3 on 2026-06-08 10:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('grade_point', models.FloatField(default=1.0, help_text='Puntos/valor de la pregunta en la evaluación', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='onlinecourse.course')),
            ],
        ),
    ]
